### ISSUE TITLE
Plugging in headphones doesn't change sound output

### ISSUE THREAD

**Issue by youssmak** [voxeet/voxeet-cordova-conferencekit#10]
# Expected Behavior

Switch sound output to headphones

# Actual Behavior

I have to touch the speaker button to switch the sound output

# Steps to Reproduce the Problem

# Workflow

  1. make a call 
  2. plug headphones

# Specifications

  - Version: Voxeet 1.0.28
  - Platform: Android 8.0
  - Subsystem: EMUI 8.0.0
  - Hardware: Honor 7X

**Comment by codlab** [comment]
Do you have the audio settings permission ?

```
    <uses-permission android:name="android.permission.MODIFY_AUDIO_SETTINGS" />
```

**Comment by youssmak** [comment]
I have the permission.
A case when it occurs: plug headphones before joining a call.
It works well if i plug the headphones after a video conf is established.

**Comment by codlab** [comment]
The fix should be available for this last item really soon. Currently testing

**Comment by youssmak** [comment]
seems to be fixed now. thanks !

**Comment by youssmak** [comment]
Many of our team members have bluetooth headphones.
Having bluetooth headphones before joining a call doesn't make the sound comes out on headphones.
Touching the speaker button is fixing it.

**Comment by codlab** [comment]
only reproduced for the bluetooth headset

**Comment by codlab** [comment]
It will be shipped into the native 1.4.11 version. Since this version is bumping the compatibility support to the Android 28, I'm working on the list of compatibility libraries it's built against to help integrate or upgrade in case of incompatibility with used libraries

**Comment by codlab** [comment]
A sample has been pushed a moment ago. It adds the various evolution for the Android platform. You can clone it from [here](https://github.com/voxeet/voxeet-cordova-sample)

**Comment by youssmak** [comment]
seems to be fixed.
thank you for the quick fix 👍
