### ISSUE TITLE
Unwanted call when coming from the background to the foreground

### ISSUE THREAD

**Issue by youssmak** [voxeet/voxeet-cordova-conferencekit#11]
# Expected Behavior

Doesn't re-call a previous call if current user has ended a conversation

# Actual Behavior

When the app is coming from the background to the foreground, the last call is launched even if current user has ended the call with the hang up red button

# Steps to Reproduce the Problem

- install your app in production mode :
here is my cmd :
```
cordova build android --release -- --versionCode=XX --gradleArg=-PcdvMinSdkVersion=19 --gradleArg=-PcdvBuildArch=x86 --verbose

jarsigner -verbose -sigalg SHA1withRSA -digestalg SHA1 -keystore app.keystore ./platforms/android/app/build/outputs/apk/release/app-release-unsigned.apk app 

zipalign -v 4 ./platforms/android/app/build/outputs/apk/release/app-release-unsigned.apk ./platforms/android/app.apk

adb install -r platforms/android/app.apk
``` 

## Workflow

- make a call
- stop the call
- put the app in the background
- re-put the app in the foreground

## Minimalistic code

same as in the README
```
Voxeet.initializeToken(access_token, refresh_token)
    .then(() => Voxeet.defaultBuiltInSpeaker(true))
    .then(() => Voxeet.defaultVideo(true))
    .then(() => Voxeet.connect(new UserInfo(this.currentUser.id, this.currentUser.displayname, this.currentUser.avatar)))
    .then(() => Voxeet.create({conferenceAlias: confId})
    .then(result => Voxeet.join(result.conferenceId))
    .catch(err => console.log(error));
```
# Specifications

- Version: Voxeet 1.0.28
- Platform: Android 8.0
- Subsystem: EMUI 8.0.0
- Hardware: Honor 7X

**Comment by youssmak** [comment]
Cannot reproduce the issue if the android apk package is not builded in release mode

**Comment by youssmak** [comment]
Fixed in the latest release. thank you

**Comment by youssmak** [comment]
Still able to reproduce it finally. You have to delete the app to reproduce it, to be able to accept the permissions again. 
Killing the app in the background and relaunching it is fixing the issue.

### Workflow

  1. Delete your android app
  2. Reinstall your android app
  3. start a call from another device (web app for example)
  4. join the call from the android app
  5. accept the permissions to access microphone ...
  6. exit the call 
  7. put the app in the background
  8. put the app in the foreground

**Comment by codlab** [comment]
Given the following sample code and the standard Android lifecycle of apps, this behaviour is completely possible when Cordova's lifecycle is resetted by the system.

```
Voxeet.initializeToken(access_token, refresh_token)
    .then(() => Voxeet.defaultBuiltInSpeaker(true))
    .then(() => Voxeet.defaultVideo(true))
    .then(() => Voxeet.connect(new UserInfo(this.currentUser.id, this.currentUser.displayname, this.currentUser.avatar)))
    .then(() => Voxeet.create({conferenceAlias: confId})
    .then(result => Voxeet.join(result.conferenceId))
    .catch(err => console.log(error));
```

**Comment by youssmak** [comment]
what do you mean ? the issue cannot be fixed ?
The sample code is the cordova example present in the README
This bug only occurs on a fresh install,  after you accept the permissions to access the mic / camera.

**Comment by codlab** [comment]
In you apk, this happens every time. Never in the repository which is being created right now (full impl soon, for now only the www folder)

**Comment by codlab** [comment]
Here is the link to the current code. The full project should be available soon. [here](https://github.com/voxeet/voxeet-cordova-sample)

**Comment by youssmak** [comment]
It happens everytime the app is deleted, to accept the permissions again.
If you hard kill the app (remove it from background), this issue will be fixed on our app.

I will check your implementation.

**Comment by codlab** [comment]
we can reproduce with your app at a 100% "success" rate if we make the app to go the task manager (or home button) and then switch back to it

Without deleting it. Something not hapenning in the sample

**Comment by codlab** [comment]
Found and fixed, I did not followed the workflow properly. I can reproduce when the app is running while the mic permission was requested

**Comment by codlab** [comment]
A sample has been pushed a moment ago. It adds the various evolution for the Android platform. You can clone it from [here](https://github.com/voxeet/voxeet-cordova-sample)

**Comment by youssmak** [comment]
Seems to be definitely fixed.
Thank you
