### ISSUE TITLE
Voxeet.defaultVideo(true) is not working when you accept an incoming call on an android device

### ISSUE THREAD

**Issue by shawnjung** [voxeet/voxeet-cordova-conferencekit#13]
**Describe the bug**

on an Android device, `Voxeet.defaultVideo(true)` setting is ignored when you accept an incoming call.

**Expected Behaviour**

when I accept the incoming call, I expect the camera (video) is on by default, but it was off.

**Steps to Reproduce the Problem**

  1. Initialize SDK with the `Voxeet.defaultVideo(true)`
  2. Trigger invitation from another device.
  3. Accept the incoming call
  4. The receiver's camera is not turned on.

**Minimalistic code (recommended)**

Cordova app:

```js
const voxeetUserInfo = new UserInfo(
  "https://app.lvh.me:4000/assets/placeholders/patient-other.png",
  "Shawn Jung",
  "patient-ca-db44b0dc-ede0-4dad-9400-e3b7b7c8f087"
)

await Voxeet.initialize(consumerKey, consumerSecret)
await Voxeet.appearMaximized(true)
await Voxeet.defaultBuiltInSpeaker(true)
await Voxeet.defaultVideo(true)
await Voxeet.connect(voxeetUserInfo)
```

**Specifications**

* Device: Samsung S9
* OS: 8.0.0
* Platform: Android
* Subsystem: N/A
* Version:
  
  * Voxeet Cordova Conference kit (commit: [71f1c3b](https://github.com/voxeet/voxeet-cordova-conferencekit/commit/71f1c3bd5060d6f5a3fcd33c9591a2821bfff1a7))
  * com.android.support:support-v13:27.+
  * com.google.firebase:firebase-messaging:11.6.2
  * com.google.firebase:firebase-dynamic-links:11.6.2
  * com.google.firebase:firebase-core:11.6.2
* Hardware: N/A

**Comment by codlab** [comment]
Note that the underlying SDK does use upgraded dependencies. In case of any break in your librarie, please add below the information. I think that the only issue you may have is concerning Firebase which is now `17.3.4` to match the build system 28 due to deprecated gradle from the end 2018

**Comment by shawnjung** [comment]
upgraded firebase messaging to 17.3.4 and seems it is resolved
