### ISSUE TITLE
Unable to run app on iOS 12 Beta 

### ISSUE THREAD

**Issue by youssmak** [voxeet/voxeet-cordova-conferencekit#2]
`dyld: Symbol not found: __T0BOWV
  Referenced from: /private/var/containers/Bundle/Application/*/*.app/Frameworks/VoxeetSDK.framework/VoxeetSDK
  Expected in: /private/var/containers/Bundle/Application/*/*.app/Frameworks/libswiftCore.dylib
 in /private/var/containers/Bundle/Application/*/*.app/Frameworks/VoxeetSDK.framework/VoxeetSDK
(lldb)`

It works well on iOS 11

**Comment by ghaiat** [comment]
hello
any update on this ? we re facing the same issue

**Comment by Comanga** [comment]
Hello, have you followed these steps:
https://github.com/voxeet/voxeet-cordova-conferencekit#ios

I think your error comes from this point: set ALWAYS_EMBED_SWIFT_STANDARD_LIBRARIES in Xcode build settings to true

**Comment by ghaiat** [comment]
Hello , i just checked and it is set to true

**Comment by ghaiat** [comment]
![image](https://user-images.githubusercontent.com/5446909/49384216-71789500-f712-11e8-9093-63eec6dc0d74.png)

**Comment by Comanga** [comment]
I can reproduce this crash if I set ALWAYS_EMBED_SWIFT_STANDARD_LIBRARIES to NO:
dyld: Library not loaded: @rpath/libswiftAVFoundation.dylib
  Referenced from: /private/var/containers/Bundle/Application/1571F2B6-8E7B-4ABC-B873-67F59A875A91/CordovaVCK.app/Frameworks/VoxeetConferenceKit.framework/VoxeetConferenceKit
  Reason: image not found

Make sure to set ALWAYS_EMBED_SWIFT_STANDARD_LIBRARIES YES is on the right target.

<img width="827" alt="screen shot 2018-12-03 at 4 52 39 pm" src="https://user-images.githubusercontent.com/6548634/49384714-e69c9800-f71b-11e8-8667-0eaf87abbaba.png">

**Comment by Comanga** [comment]
Do you have the same crash? What's your Xcode version?

**Comment by weiz18** [comment]
@Comanga Our Xcode Version is 10.1

**Comment by weiz18** [comment]
dyld: Symbol not found: __T0BOWV
  Referenced from: /private/var/containers/Bundle/Application/*/Operations.app/Frameworks/VoxeetSDK.framework/VoxeetSDK
  Expected in: /private/var/containers/Bundle/Application/*/Operations.app/Frameworks/libswiftCore.dylib
 in /private/var/containers/Bundle/Application/*/Operations.app/Frameworks/VoxeetSDK.framework/VoxeetSDK

**Comment by weiz18** [comment]
Hey, 

Do you think it is related to the version of swift? 

thanks

**Comment by weiz18** [comment]
Hey @Comanga 
Your solution works. thanks for the help.
