### ISSUE TITLE
[Android] Support Android API 34

### ISSUE THREAD

**Issue by gabides** [voxeet/voxeet-cordova-conferencekit#86]
Hello, are you planning to support android sdk 34? We can't build our app with the latest released version of the plugin when we target version 34 (seems that the plugin has not been updated for 2 years when checking the code from master branch)

Thanks!

**Comment by codlab** [comment]
@FabienLavocat will be able to tell more

**Comment by FabienLavocat** [comment]
We have received your support ticket and will follow up there.
