### ISSUE TITLE
The screen turns off during a videoconference

### ISSUE THREAD

**Issue by JeanCarriere** [voxeet/voxeet-cordova-conferencekit#9]
# Expected Behavior
The phone / the screen should not go into stand by mode during a videoconference

# Steps to Reproduce the Problem
## Workflow
  1. On android launch a videoconference
  2. Do not touch the phone
  3. The screen goes black

# Specifications
Android 8.0.0 (Samsung S7 Samsung experience 9.0)

**Comment by youssmak** [comment]
@codlab not fixed in the latest release. I have reproduced too

**Comment by codlab** [comment]
Is the WAKE_LOCK permission properly set in the AndroidManifest ?

**Comment by youssmak** [comment]
I have it 
`<uses-permission android:name="android.permission.WAKE_LOCK" />`

**Comment by youssmak** [comment]
To reproduce, please make sure that there is no connected cable to the phone : no debug mode and telephone is not in charge.

**Comment by bsenard** [comment]
@JeanCarriere show me this bug, we will try to reproduce it

**Comment by codlab** [comment]
Fix in the next version (available in internal 1.4.6+ sdk)

**Comment by youssmak** [comment]
Fixed in the latest release 👍
will reopen it if a talkspirit team member is still able to reproduce it

**Comment by youssmak** [comment]
Still able to reproduce it. The screen is fading after but is not turning off anymore.
Could you please reopen the issue ?

**Comment by youssmak** [comment]
* Version: Voxeet 1.0.30
* Platform: Android 8.0
* Subsystem: EMUI 8.0.0
* Hardware: Honor 7X
